### ISSUE TITLE
Laravel 7 Support 

### ISSUE THREAD

**Issue by AshrafSarsour** [betapeak/laravel-godaddy#5]
Problem 1
    - Conclusion: don't install betapeak/laravel-godaddy 1.0.1
    - Conclusion: remove laravel/framework v7.26.1
    - Installation request for betapeak/laravel-godaddy ^1.0 -> satisfiable by betapeak/laravel-godaddy[1.0.0, 1.0.1].
    - Conclusion: don't install laravel/framework v7.26.1
    - betapeak/laravel-godaddy 1.0.0 requires illuminate/support ~5.3.0|~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.3.x-dev, 5.4.x-dev, 5.5.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - illuminate/support 5.3.x-dev conflicts with laravel/framework[v7.26.1].
    - illuminate/support 5.4.x-dev conflicts with laravel/framework[v7.26.1].
    - illuminate/support 5.5.x-dev conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.3.0 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.3.16 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.3.23 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.3.4 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.4.0 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.4.13 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.4.17 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.4.19 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.4.27 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.4.36 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.4.9 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.0 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.16 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.17 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.2 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.28 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.35 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.36 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.37 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.39 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.40 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.41 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.43 conflicts with laravel/framework[v7.26.1].
    - illuminate/support v5.5.44 conflicts with laravel/framework[v7.26.1].
    - don't install illuminate/support v5.5.33|don't install laravel/framework v7.26.1
    - don't install illuminate/support v5.5.34|don't install laravel/framework v7.26.1
    - Installation request for laravel/framework (locked at v7.26.1, required as ^7.0) -> satisfiable by laravel/framework[v7.26.1].

**Comment by ymslavov** [comment]
Resolved in 1.0.3
